services:
  backend:
    build:
      context: ../
      dockerfile: docker/stack/backend/Dockerfile.dev
    volumes:
      - ../backend:/app

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DESIGN: "nette" # themes: https://github.com/vrana/adminer/tree/master/plugins
    networks:
      - simple_bank

  caddy:
    volumes:
      - ./caddy/dev/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      ADMINER_PORT: ${ADMINER_PORT}
