services:
  backend:
    build:
      context: ../
      dockerfile: docker/stack/backend/Dockerfile.dev
    volumes:
      - ../:/app

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DESIGN: "nette" # themes: https://github.com/vrana/adminer/tree/master/plugins
    networks:
      - simple_bank
