version: "3.9"

services:
  backend:
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT}:8001
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
    networks:
      - simple_bank

  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-h",
          "localhost",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - simple_bank

volumes:
  postgres:

networks:
  simple_bank:
