FROM golang:1.22.1-alpine 

RUN apk add --no-cache gcc musl-dev
ENV CGO_ENABLED=1

# Install tools
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.26.0 && \
    go install github.com/githubnemo/CompileDaemon@v1.4.0 && \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.17.1

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download && go mod verify

COPY . .

COPY docker/stack/backend/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "entrypoint.sh" ]

EXPOSE 8001

CMD CompileDaemon -log-prefix=false -build="go build -o bin/simple_bank main.go" -command="bin/simple_bank"
