name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"

      - name: Go version
        run: go version

      - name: Start containers
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: simple-bank
        run: make start/dev arg=-d

        # @TODO: when backend docker container is set
        # run `make migratup` before run backend container
      - name: Wait for docker to finish building
        run: sleep 10

      - name: Apply database migrations
        run: make migratup

      - name: Backend test
        run: make test
