name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"

      - name: Go version
        run: go version

      - name: Start containers
        run: make start/dev arg=-d

      - name: Test
        run: make test
