name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version-file: "go.mod"

      - name: Go version
        run: go version

      - name: Start containers
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          ADMINER_PORT: ${{ secrets.ADMINER_PORT }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: make start/dev arg=-d

      - name: Sleep
        run: sleep 10

      - name: Running containers
        run: docker ps -a

      - name: Backend test
        run: make test
